### ISSUE TITLE
Implement WebSocket Support for 2048 Game

### ISSUE THREAD

**Issue by briansinw3b** [decolgen-labs/starkarcade-monorepo#8]
### Description
We need to create a WebSocket integration for our single-player 2048 game that allows players to claim on-chain points on the StarkARCADE Hubs. This feature aims to enhance the gaming experience by enabling real-time communication between the game and the blockchain, ensuring seamless and secure point claiming.

### Requirements
1. **WebSocket Server Setup**

      Implement a WebSocket server that listens for game events.
      Ensure the server can handle multiple connections and is scalable.

2. **Game Integration**

      Modify the existing 2048 game code to send game events (e.g., game over, score updates) to the WebSocket server.
      Ensure the game can establish and maintain a stable WebSocket connection.

3. **Blockchain Interaction**

      Use StarkNet’s APIs to claim points on the blockchain.
      Ensure the WebSocket server securely handles and processes the game data before interacting with StarkNet.
      Implement authentication mechanisms to verify the identity of players before allowing point claims.

4. **Data Handling**

      Define the data structure for messages exchanged between the game and the WebSocket server.
      Ensure all game events are correctly formatted and validated before being sent to the blockchain.

5. **Security**

      Implement necessary security measures to protect WebSocket communication.
      Ensure data integrity and prevent tampering of game events and blockchain transactions.

6. **Testing**

      Write unit and integration tests for the WebSocket server.
      Perform end-to-end testing to ensure the entire workflow (game event -> WebSocket -> StarkNet) functions correctly.

### Tasks

- Set up a basic WebSocket server using a suitable framework (e.g., NestJs with `socket.io` library).
- Modify the 2048 game to include WebSocket client functionality.
- Define and implement the protocol for communication between the game and the WebSocket server.
- Integrate StarkNet API calls in the WebSocket server to handle point claims.
- Implement authentication and security measures.
- Write tests to cover all new functionality.

### Acceptance Criteria

- A functioning WebSocket server capable of receiving game events and processing point claims on StarkNet.
- The 2048 game should successfully connect to the WebSocket server and send relevant events.
- Points claimed on StarkNet should reflect the player's score accurately.
- All implemented features should pass the defined tests.

**Comment by josephchimebuka** [comment]
@briansinw3b if you don't mind I would like to contribute to this project
