### ISSUE TITLE
Implement WebSocket Support for Tetris Game

### ISSUE THREAD

**Issue by briansinw3b** [decolgen-labs/starkarcade-monorepo#9]
### Description
We need to create a WebSocket integration for our single-player Tetris game that allows players to claim points on the StarkNet blockchain. This integration will enable real-time communication between the game and the blockchain, providing a seamless and secure way for players to claim their scores as points on StarkNet.

### Requirements
1. **WebSocket Server Setup**

      Implement a WebSocket server that can handle incoming connections and game events.
      Ensure the server is scalable and can support multiple simultaneous connections.

2. **Game Integration**

      Modify the existing Tetris game code to send game events (e.g., line clear, game over, score updates) to the WebSocket server.
      Ensure the game maintains a stable WebSocket connection throughout the gameplay session.
      Blockchain Interaction:
      
      Utilize StarkNet’s APIs to claim points based on the player's score.
      Ensure the WebSocket server securely processes and validates game data before interacting with StarkNet.
      Implement authentication mechanisms to verify player identities before allowing point claims.
3. **Data Handling**

      Define a structured format for the messages exchanged between the Tetris game and the WebSocket server.
      Validate and format game events correctly before sending them to the blockchain.

4. **Security**

      Implement robust security measures to protect the integrity of WebSocket communication.
      Ensure the authenticity and integrity of game events and blockchain transactions.
5. **Testing**

      Develop unit and integration tests for the WebSocket server.
      Conduct end-to-end testing to ensure the entire workflow (game event -> WebSocket -> StarkNet) functions as expected.

### Tasks

- Set up a basic WebSocket server using a suitable framework (e.g., Node.js with ws library).
- Modify the Tetris game to include WebSocket client functionality.
- Define and implement the communication protocol between the Tetris game and the WebSocket server.
- Integrate StarkNet API calls within the WebSocket server to handle point claims.
- Implement authentication and necessary security measures.
- Write comprehensive tests to cover all new functionality.

### Acceptance Criteria

- A fully functional WebSocket server capable of receiving and processing game events from the Tetris game.
- The Tetris game successfully connects to the WebSocket server and sends relevant game events.
- Players' points claimed on StarkNet accurately reflect their in-game scores.
- All implemented features pass the defined tests.

**Comment by josephchimebuka** [comment]
@briansinw3b I would like to help contribute to this project. I can write a client side web socket that will communicate with the server web socket

**Comment by od-hunter** [comment]
Hi @briansinw3b , can I be assigned this issue please? I'll set up a scalable WebSocket server using Node.js with the ws library, modify the Tetris game to send game events to the WebSocket server, then I'll Integrate StarkNet APIs in the server to claim points based on player scores (ensuring data validation and security), then I'll implement authentication to verify player identities.
Please assign me.
